#!/usr/bin/python

import sys
import json
import socket

# The code is not fancy or elegant, but it works.
#
# Paul McGowan 2021


# Add the names of your blinds here together with
# the IP address of your bridge.
blinds = ["dining","patio","bedroom","study","ella"]
server = ("10.10.255.66", 32100)

def sanityCheck():
   if blind == "0000":
      print "Unknown blind name "+bln
      exit(0)
   if data <> "operation":
      if command.isdigit() == True:
         pct = int(command)
         if pct < 0 or pct > 100:
            print "Blind movement must be between 0 and 100"
            exit(0)
      else:
         print "Blind movement must be numeric and between 0 and 100"
         exit(0)

if len(sys.argv) <> 3:
   print "blind [name] [open/close/up/down/stop/query/status/0-100]"
   exit(0)

bln = sys.argv[1]
command = sys.argv[2]
buffer = 1024
blind = "0000"
operation = command
data = "targetPosition"

cmds = ["close","down","open","up","stop","halt","status","query"]
ops = ["0","0","1","1","2","2","5","5"]
c = 0
for x in cmds:
   if command == x:
      operation = ops[c]
      data = "operation"
   c += 1

c = 0
for x in blinds:
   c += 1
   if bln == x:
      blind = "000" + str(c)

sanityCheck()

Payload = str.encode('{"msgType":"WriteDevice",\
                        "mac":"--MAC--'+blind+'",\
                        "DeviceType":"10000000",\
                        "AccessToken":"--TOKEN--",\
                        "msgID":"21200331105735705",\
                        "data":{"'+data+'":'+operation+'}\
                      }')

UDPClientSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)
UDPClientSocket.sendto(Payload, server)
response = UDPClientSocket.recvfrom(buffer)
print(json.dumps(json.loads(format(response[0])), indent=4, sort_keys=True))
