#!/usr/bin/python

import json
import socket

server  = ("++IP OF HUB+++", 32100)
payload = str.encode('{"msgType":"GetDeviceList","msgID":"2023465678"}')
buffer  = 1024

UDPClientSocket = socket.socket(family=socket.AF_INET, type=socket.SOCK_DGRAM)
UDPClientSocket.sendto(payload, server)
response = UDPClientSocket.recvfrom(buffer)
data = json.loads(json.dumps(json.loads(format(response[0])), indent=4, sort_keys=True))
#print(json.dumps(json.loads(format(response[0])), indent=4, sort_keys=True))
print ("Firmware Version "+(str(data["fwVersion"])))
print ("MAC address "+(str(data["mac"])))
print ("Token "+(str(data["token"])))
