#!/usr/bin/python3

import binascii
from Crypto.Cipher import AES

data = '+++++TOKEN++++++';
key = '+++++++KEY++++++';

print ((binascii.hexlify(AES.new(key, AES.MODE_ECB).encrypt(data)).upper()).decode())
