#!/usr/bin/python3

import binascii
from Crypto.Cipher import AES

data = '+++++TOKEN++++++';
key = '+++++++KEY++++++';
aes = AES.new(key, AES.MODE_ECB)
enc = (binascii.hexlify(aes.encrypt(data)).upper()).decode()
print (enc)
